# Generated by Django 4.1.3 on 2022-11-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('NIK', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='images')),
                ('Alamat', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
