# Generated by Django 4.2.30 on 2026-05-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_postmodel_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="aes_key",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="NIK",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="Nama",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="Password",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=models.CharField(
                blank=True, default="default.png", max_length=255, null=True
            ),
        ),
    ]
