# Generated by Django 4.2.30 on 2026-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_postmodel_aes_key_alter_postmodel_nik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="image_ciphertext",
            field=models.TextField(blank=True, default=""),
        ),
    ]
