# Generated by Django 4.2.30 on 2026-08-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_postmodel_key_salt_postmodel_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="jenis_kelamin",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="nama_ayah",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="nama_ibu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="nik_ayah",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="nik_ibu",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="no_kk",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="tanggal_lahir",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="tempat_lahir",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="postmodel",
            name="Password",
            field=models.TextField(blank=True, default=""),
        ),
    ]
