# Generated by Django 4.2.30 on 2026-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_postmodel_jenis_kelamin_postmodel_nama_ayah_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="agama",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="jenis_pekerjaan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="kewarganegaraan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="pendidikan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="status_hubungan_keluarga",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="status_perkawinan",
            field=models.TextField(blank=True, default=""),
        ),
    ]
