# Generated by Django 4.2.30 on 2026-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_postmodel_agama_postmodel_jenis_pekerjaan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="no_kitap",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="no_paspor",
            field=models.TextField(blank=True, default=""),
        ),
    ]
