# Generated by Django 4.2.30 on 2026-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_postmodel_no_kitap_postmodel_no_paspor"),
    ]

    operations = [
        migrations.AddField(
            model_name="postmodel",
            name="desa_kelurahan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="kabupaten_kota",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="kecamatan",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="kode_pos",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="nama_kepala_desa",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="provinsi",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="rt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="postmodel",
            name="rw",
            field=models.TextField(blank=True, default=""),
        ),
    ]
